### PR TITLE
Documentation updates + Github Pages site

### PR DESCRIPTION
**Pull request by sdijoseph**
This PR addresses #209. 

- I added a bunch of missing XML tags and created a docfx project + workflow to publish the docs to a GitHub Pages site. You can preview the site [here](https://sdijoseph.github.io/LibUsbDotNet/api/index.html).
- I also updated and unified the copyright notice, including fixing an annoying issue where the copyright symbol was not UTF-8 encoded in some of the files.
- Switched the solution to file-scope namespaces. It's not directly related to documentation but it has no functional effect.

I'm leaving this as a draft for now, as I need to fill out the articles portion of the docs site.

### CODE REVIEW

**Comment by sdijoseph** [comment]
@mcuee Ok I think this is ready to go now, I just made some edits to the readme and added it to the site. We can add to it over time (with articles, examples, etc.). Let me know if [this looks good to you.](https://sdijoseph.github.io/LibUsbDotNet/)

The site should get built on every push to master.

**Comment by mcuee** [comment]
@sdijoseph 

This is great. Please just update to sort out the minor conflict now that PR #212 is merged.

**Comment by sdijoseph** [comment]
@mcuee Ready to go.

**Comment by sdijoseph** [comment]
@mcuee I forgot to mention, you need to follow the [steps here](https://docs.github.com/en/pages/quickstart#creating-your-website) from step 3 onward in order for the site to actually deploy. Select "gh-pages" as the publishing source.

**Comment by mcuee** [comment]
@sdijoseph 

Ah I see. Right now I do not have the necessary permission yet for this repo. I will check with @qmfrederik.

@qmfrederik 
Please help here. Thanks.

**Pull request merged**
