### PR TITLE
Build for linux-arm

### PR DESCRIPTION
**Pull request by exelix11**
Someone already asked this in the issue tracker https://github.com/LibUsbDotNet/LibUsbDotNet/issues/85 but got no response.

This PR adds native methods generation and building for linux-arm.

I tested on a raspberry pi 3 with bulk and interrupt transfers, seems to work fine.

### CODE REVIEW

**Comment by exelix11** [comment]
Uhm not sure what does `Error: Failed request: (statusCode) 404`  mean for osx but don't think it's caused by my changes, unfortunately don't have a mac to test. Any help is appreciated.

**Comment by smuellener** [comment]
@exelix11 why was your PR not merged? Is the library working for you still on linux-arm ?

**Comment by exelix11** [comment]
Yes it does work for me, tested on a raspberry pi 3. Don't know why no maintainer has replied, i ended up adding my fork as a submodule in the project where i need it and importing it as a local nuget package.

**Comment by smuellener** [comment]
@qmfrederik my first tests are also working on an NXP iMX6 processor (also linux-arm). Can we merge this one in? Thanks

**Comment by doug62** [comment]
+1 Merging this - Would love to USB-ize my Raspberry!  Made the change locally but the build doesn't like me using VS2019, guessing i have to install some build tools....

**Comment by qmfrederik** [comment]
Sorry for the wait. I've triggered a rebuild, if CI is green, this should be good to merge. Thanks!

**Comment by qmfrederik** [comment]
I'm not sure about the OSX build failure. It looks like it's an issue with Azure DevOps. It may be temporary, I'll retrigger the build later today.

**Comment by doug62** [comment]
@qmfrederik  - Looks like build failed near: 2020-12-01T18:35:43.1674080Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/download-build-artifacts
2020-12-01T18:35:43.1675910Z ==============================================================================
2020-12-01T18:35:45.5417270Z Downloading artifacts for build: 155
2020-12-01T18:35:45.9418540Z Downloading items from container resource #/9525563/drop
2020-12-01T18:35:45.9423150Z Downloading artifact drop from: https://dev.azure.com/libusbdotnet//_apis/resources/Containers/9525563?itemPath=drop&isShallow=true&api-version=4.1-preview.4

**Comment by exelix11** [comment]
> I'm not sure about the OSX build failure. It looks like it's an issue with Azure DevOps. It may be temporary

@qmfrederik I don't know about this, it's the same error from back in july when i made the PR, doubt it's going away on its own.

The relevant part in the log is
> Downloading artifacts for build: 155
Downloading items from container resource #/9525563/drop
Downloading artifact drop from: https://dev.azure.com/libusbdotnet//_apis/resources/Containers/9525563?itemPath=drop&isShallow=true&api-version=4.1-preview.4
Retrying download of , retry count: 1
Retrying download of , retry count: 2
Retrying download of , retry count: 3
Retrying download of , retry count: 4
Successfully downloaded artifacts to /Users/runner/work/1/a
##[error]Error: Failed request: (statusCode) 404

Maybe it's an outdated version of the pipeline in my branch ?  Could the artifact url be wrong ?
I'd try cloning master or some other branch that works for sure and triggering a build there.

**Pull request merged**
