### PR TITLE
Fix the PortNumbers property.

### PR DESCRIPTION
**Pull request by sdijoseph**
Fixes the PortNumbers property so that it doesn't always throw an exception.

### CODE REVIEW

**Comment by mcuee** [comment]
@qmfrederik 

Please help to review this patch. Thanks.

**Comment by mcuee** [comment]
@sdijoseph 

Could you privide a simple sample code to demonstrate the issue so that I can test this out? Thanks. Then I can test it out and merge the PR if the test result is positive.

**Comment by sdijoseph** [comment]
> @sdijoseph
> 
> Could you privide a simple sample code to demonstrate the issue so that I can test this out? Thanks. Then I can test it out and merge the PR if the test result is positive.

```
using LibUsbDotNet.LibUsb;

UsbContext context = new UsbContext();

using var devices = context.List();

foreach (UsbDevice device in devices)
{
    Console.Write($"Device with VID: {device.VendorId:X4} PID: {device.ProductId:X4} has location id : Bus {device.BusNumber} Ports ");
    for (int i = 0; i < device.PortNumbers.Count; i++)
    {
        Console.Write($"{device.PortNumbers[i]}");
        if (i != device.PortNumbers.Count - 1)
            Console.Write(", ");
    }
    Console.WriteLine();
}
```
Sure, the above code throws this error on the main branch:

```
Device with VID: 04B4 PID: 00F0 has location id : Bus 6 Ports Unhandled exception. LibUsbDotNet.LibUsb.UsbException: Other error
   at LibUsbDotNet.LibUsb.ErrorExtensions.ThrowOnError(Error error) in /home/sdijoseph/Coding/LibUsbDotNet/src/LibUsbDotNet/LibUsb/ErrorExtensions.cs:line 38
   at LibUsbDotNet.LibUsb.UsbDevice.get_PortNumbers() in /home/sdijoseph/Coding/LibUsbDotNet/src/LibUsbDotNet/LibUsb/UsbDevice.Device.cs:line 144
   at Program.<Main>$(String[] args) in /home/sdijoseph/Coding/LibUsbTests/LibUsbTests/Program.cs:line 12
```
With the PR, on my machine it prints:

```
Device with VID: 04B4 PID: 00F0 has location id : Bus 6 Ports 4
Device with VID: 04E8 PID: 6860 has location id : Bus 6 Ports 3
Device with VID: 1D6B PID: 0003 has location id : Bus 6 Ports 
Device with VID: 1B1C PID: 0A13 has location id : Bus 5 Ports 2
Device with VID: 046D PID: C24A has location id : Bus 5 Ports 1
Device with VID: 1D6B PID: 0002 has location id : Bus 5 Ports 
Device with VID: 1D6B PID: 0003 has location id : Bus 4 Ports 
Device with VID: 1D6B PID: 0002 has location id : Bus 3 Ports 
Device with VID: 1D6B PID: 0003 has location id : Bus 2 Ports 
Device with VID: 04F3 PID: 2014 has location id : Bus 1 Ports 9
Device with VID: 1B1C PID: 0A14 has location id : Bus 1 Ports 8
Device with VID: 8087 PID: 0025 has location id : Bus 1 Ports 2
Device with VID: 1D6B PID: 0002 has location id : Bus 1 Ports 

Process finished with exit code 0.

```

The reason is the main branch is calling `ThrowOnError` on the 'NativeMethods.GetPortNumbers' method, which throws an error on any non-zero value, where as `libusb_get_port_numbers` returns a positive integer representing the length of the port tree, and a negative integer on error.

**Comment by mcuee** [comment]
Tested to be good under Windows.

```
PS C:\work\libusb\libusbdotnet\libusbdotnet_pr192> type .\src\Examples\Show.Info\ShowInfo.cs
using LibUsbDotNet.Info;
using LibUsbDotNet.LibUsb;
using System;
using System.Collections.ObjectModel;

namespace Examples
{
    internal class ShowInfo
    {
        public static void Main(string[] args)
        {

                        UsbContext context = new UsbContext();

                        using var devices = context.List();

                        foreach (UsbDevice device in devices)
                        {
                                Console.Write($"Device with VID: {device.VendorId:X4} PID: {device.ProductId:X4} has location id : Bus {device.BusNumber} Ports ");
                                for (int i = 0; i < device.PortNumbers.Count; i++)
                                {
                                        Console.Write($"{device.PortNumbers[i]}");
                                        if (i != device.PortNumbers.Count - 1)
                                                Console.Write(", ");
                                }
                                Console.WriteLine();
                        }

            // Wait for user input..
            Console.WriteLine("Press any key to exit");
            Console.ReadKey();
        }
    }
}

PS C:\work\libusb\libusbdotnet\libusbdotnet_pr192> dotnet run --project .\src\Examples\Show.Info\Show.Info.csproj -c Release
Device with VID: 05E3 PID: 0612 has location id : Bus 2 Ports 2
Device with VID: 8087 PID: 0026 has location id : Bus 1 Ports 10
Device with VID: 04F2 PID: B6DD has location id : Bus 1 Ports 5
Device with VID: 1C7A PID: 0575 has location id : Bus 1 Ports 7
Device with VID: 8086 PID: A0ED has location id : Bus 1 Ports
Device with VID: 05E3 PID: 0610 has location id : Bus 1 Ports 2
Device with VID: 04D8 PID: FA2E has location id : Bus 1 Ports 2, 3
Device with VID: 046D PID: C52B has location id : Bus 1 Ports 3
Device with VID: 8086 PID: 9A13 has location id : Bus 2 Ports
Press any key to exit
```


```

**Comment by mcuee** [comment]
@sdijoseph 

The only question is whether you want to assign Port Number 0 to the root hub to be in line with libusb. I tend to think it is a good idea.

**Comment by mcuee** [comment]
Good under Linux as well.

```
mcuee@UbuntuSwift3:~/build/libusbdotnet_pr192$ dotnet run --project ./src/Examples/Show.Info/Show.Info.csproj -c Release
Device with VID: 1D6B PID: 0003 has location id : Bus 4 Ports 
Device with VID: 1C7A PID: 0575 has location id : Bus 3 Ports 7
Device with VID: 04F2 PID: B6DD has location id : Bus 3 Ports 5
Device with VID: 046D PID: C52B has location id : Bus 3 Ports 3
Device with VID: 04D8 PID: FA2E has location id : Bus 3 Ports 2, 3
Device with VID: 05E3 PID: 0610 has location id : Bus 3 Ports 2
Device with VID: 8087 PID: 0026 has location id : Bus 3 Ports 10
Device with VID: 1D6B PID: 0002 has location id : Bus 3 Ports 
Device with VID: 05E3 PID: 0612 has location id : Bus 2 Ports 1
Device with VID: 1D6B PID: 0003 has location id : Bus 2 Ports 
Device with VID: 1D6B PID: 0002 has location id : Bus 1 Ports 
Press any key to exit

mcuee@UbuntuSwift3:~/build/libusbdotnet_pr192$ lsusb
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 006: ID 1c7a:0575 LighTuning Technology Inc. EgisTec EH575
Bus 003 Device 005: ID 04f2:b6dd Chicony Electronics Co., Ltd HD User Facing
Bus 003 Device 003: ID 046d:c52b Logitech, Inc. Unifying Receiver
Bus 003 Device 004: ID 04d8:fa2e Microchip Technology, Inc. USB Receiver
Bus 003 Device 002: ID 05e3:0610 Genesys Logic, Inc. 4-port hub
Bus 003 Device 007: ID 8087:0026 Intel Corp. 
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 002: ID 05e3:0612 Genesys Logic, Inc. Hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

mcuee@UbuntuSwift3:~/build/libusb$ ./examples/listdevs 
1d6b:0003 (bus 4, device 1)
1c7a:0575 (bus 3, device 6) path: 7
04f2:b6dd (bus 3, device 5) path: 5
046d:c52b (bus 3, device 3) path: 3
04d8:fa2e (bus 3, device 4) path: 2.3
05e3:0610 (bus 3, device 2) path: 2
8087:0026 (bus 3, device 7) path: 10
1d6b:0002 (bus 3, device 1)
05e3:0612 (bus 2, device 2) path: 1
1d6b:0003 (bus 2, device 1)
1d6b:0002 (bus 1, device 1)
```

**Pull request merged**
