### PR TITLE
Setup the management of libusbK devices on Windows

### PR DESCRIPTION
**Pull request by MatCDev**
I still have to refactor some things. However it works fine on my side.
What do you think about it ?
For any questions I am available.

### CODE REVIEW

**Comment by mcuee** [comment]
When it comes to codes, we need @qmfrederik to review. I know very little of dotnet myself.

**Comment by mcuee** [comment]
At least I can build under Windows. Let me test it later as well.

```
PS C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162> dotnet --version
6.0.203
PS C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162> dotnet build stage/BenchmarkCon/BenchmarkCon.csproj -c Release
Microsoft (R) Build Engine version 17.1.1+a02f73656 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\LibUsbDotNet.csproj (in 233 ms).
  Restored C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\BenchmarkCon\BenchmarkCon.csproj (in 233 ms).
C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\Internal\Kernel32.cs(89,62): warning CS0618: 'UnmanagedType.AsAny' is obsolete: 'Marshalling arbitrary types may be unavailable in future releases. Please specify the type you wish to marshal as.' [C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\LibUsbDotNet.csproj]
C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\Internal\Kernel32.cs(99,62): warning CS0618: 'UnmanagedType.AsAny' is obsolete: 'Marshalling arbitrary types may be unavailable in future releases. Please specify the type you wish to marshal as.' [C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\LibUsbDotNet.csproj]
C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\Internal\Kernel32.cs(119,70): warning CS0618: 'UnmanagedType.AsAny' is obsolete: 'Marshalling arbitrary types may be unavailable in future releases. Please specify the type you wish to marshal as.' [C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\LibUsbDotNet.csproj]
C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\Internal\SetupApi.cs(239,77): warning CS0618: 'UnmanagedType.AsAny' is obsolete: 'Marshalling arbitrary types may be unavailable in future releases. Please specify the type you wish to marshal as.' [C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\LibUsbDotNet.csproj]
C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\Internal\SetupApi.cs(296,81): warning CS0618: 'UnmanagedType.AsAny' is obsolete: 'Marshalling arbitrary types may be unavailable in future releases. Please specify the type you wish to marshal as.' [C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\LibUsbDotNet.csproj]
C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\WinUsb\Internal\LibusbKAPI.cs(102,78): warning CS0618: 'UnmanagedType.AsAny' is obsolete: 'Marshalling arbitrary types may be unavailable in future releases. Please specify the type you wish to marshal as.' [C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\LibUsbDotNet.csproj]
C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\WinUsb\Internal\WinUsbAPI.cs(104,78): warning CS0618: 'UnmanagedType.AsAny' is obsolete: 'Marshalling arbitrary types may be unavailable in future releases. Please specify the type you wish to marshal as.' [C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\LibUsbDotNet.csproj]
C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\LibUsb\Internal\LibUsbRequest.cs(71,30): warning CS0618: 'Marshal.ReadByte(object, int)' is obsolete: 'ReadByte(Object, Int32) may be unavailable in future releases.' [C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\LibUsbDotNet.csproj]
C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\MonoLibUsb\MonoUsbEventHandler.cs(188,25): warning SYSLIB0006: 'Thread.Abort()' is obsolete: 'Thread.Abort is not supported and throws PlatformNotSupportedException.' [C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\LibUsbDotNet.csproj]
C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\Main\UsbDeviceFinder.cs(261,20): warning SYSLIB0011: 'BinaryFormatter.Deserialize(Stream)' is obsolete: 'BinaryFormatter serialization is obsolete and should not be used. See https://aka.ms/binaryformatter for more information.' [C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\LibUsbDotNet.csproj]
C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\Main\UsbDeviceFinder.cs(272,13): warning SYSLIB0011: 'BinaryFormatter.Serialize(Stream, object)' is obsolete: 'BinaryFormatter serialization is obsolete and should not be used. See https://aka.ms/binaryformatter for more information.' [C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\LibUsbDotNet.csproj]
  LibUsbDotNet -> C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\bin\Release\net5.0\LibUsbDotNet.LibUsbDotNet.dll
  BenchmarkCon -> C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\BenchmarkCon\bin\Release\net5.0\BenchmarkCon.dll

Build succeeded.

C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\Internal\Kernel32.cs(89,62): warning CS0618: 'UnmanagedType.AsAny' is obsolete: 'Marshalling arbitrary types may be unavailable in future releases. Please specify the type you wish to marshal as.' [C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\LibUsbDotNet.csproj]
C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\Internal\Kernel32.cs(99,62): warning CS0618: 'UnmanagedType.AsAny' is obsolete: 'Marshalling arbitrary types may be unavailable in future releases. Please specify the type you wish to marshal as.' [C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\LibUsbDotNet.csproj]
C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\Internal\Kernel32.cs(119,70): warning CS0618: 'UnmanagedType.AsAny' is obsolete: 'Marshalling arbitrary types may be unavailable in future releases. Please specify the type you wish to marshal as.' [C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\LibUsbDotNet.csproj]
C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\Internal\SetupApi.cs(239,77): warning CS0618: 'UnmanagedType.AsAny' is obsolete: 'Marshalling arbitrary types may be unavailable in future releases. Please specify the type you wish to marshal as.' [C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\LibUsbDotNet.csproj]
C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\Internal\SetupApi.cs(296,81): warning CS0618: 'UnmanagedType.AsAny' is obsolete: 'Marshalling arbitrary types may be unavailable in future releases. Please specify the type you wish to marshal as.' [C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\LibUsbDotNet.csproj]
C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\WinUsb\Internal\LibusbKAPI.cs(102,78): warning CS0618: 'UnmanagedType.AsAny' is obsolete: 'Marshalling arbitrary types may be unavailable in future releases. Please specify the type you wish to marshal as.' [C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\LibUsbDotNet.csproj]
C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\WinUsb\Internal\WinUsbAPI.cs(104,78): warning CS0618: 'UnmanagedType.AsAny' is obsolete: 'Marshalling arbitrary types may be unavailable in future releases. Please specify the type you wish to marshal as.' [C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\LibUsbDotNet.csproj]
C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\LibUsb\Internal\LibUsbRequest.cs(71,30): warning CS0618: 'Marshal.ReadByte(object, int)' is obsolete: 'ReadByte(Object, Int32) may be unavailable in future releases.' [C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\LibUsbDotNet.csproj]
C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\MonoLibUsb\MonoUsbEventHandler.cs(188,25): warning SYSLIB0006: 'Thread.Abort()' is obsolete: 'Thread.Abort is not supported and throws PlatformNotSupportedException.' [C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\LibUsbDotNet.csproj]
C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\Main\UsbDeviceFinder.cs(261,20): warning SYSLIB0011: 'BinaryFormatter.Deserialize(Stream)' is obsolete: 'BinaryFormatter serialization is obsolete and should not be used. See https://aka.ms/binaryformatter for more information.' [C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\LibUsbDotNet.csproj]
C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\Main\UsbDeviceFinder.cs(272,13): warning SYSLIB0011: 'BinaryFormatter.Serialize(Stream, object)' is obsolete: 'BinaryFormatter serialization is obsolete and should not be used. See https://aka.ms/binaryformatter for more information.' [C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\LibUsbDotNet\LibUsbDotNet.csproj]
    11 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.56
```

**Comment by mcuee** [comment]
@MatCDev 
Strange, it still does not work with libusbk device.

```
S C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162> git log
commit a7cb31f8b4ce99ddba47dbde5a1e02cc221e909d (HEAD -> v2, origin/v2)
Author: MatCDev <mathieuclld@gmail.com>
Date:   Thu Jun 2 11:11:10 2022 +0200

    Setup the management of libusbK devices on Windows

PS C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\BenchmarkCon\bin\Release\net5.0> .\BenchmarkCon.exe list
LibUsbDotNet USB Benchmark v2.2.0.0
Copyright (c) 2010 Travis Robinson. <libusbdotnet@gmail.com>
website: http://sourceforge.net/projects/libusbdotnet
1. 16C0:05DC VOTI - USBasp
2. 04D8:FA2E Microchip Technology, Inc. - Benchmark Device
3. 16C0:05DC VOTI - USBasp

Select device (1-3) :2

err:device 04D2:162E not found!
Press any key to exit..
```

Once I switch to libusb-win32 or WinUSB driver, it works.
```
PS C:\work\libusb\libusbdotnet\libusbdotnet_v2_pr162\stage\BenchmarkCon\bin\Release\net5.0> .\BenchmarkCon.exe list
LibUsbDotNet USB Benchmark v2.2.0.0
Copyright (c) 2010 Travis Robinson. <libusbdotnet@gmail.com>
website: http://sourceforge.net/projects/libusbdotnet
1. 16C0:05DC VOTI - USBasp
2. 04D8:FA2E Microchip Technology, Inc. - Benchmark Device
3. 16C0:05DC VOTI - USBasp

Select device (1-3) :2

err:device 04D2:162E not found!
Press any key to exit..

```

**Comment by MatCDev** [comment]
Hi @mcuee ,
I just tested it myself, same problem with BenchmarkCon.
On my way fixing this...
I will have to modify BenchmarkCon to add the management of the new type of device ('libusbK') that I introduced in the code of the library.
However, the core of the library should still work. During my tests, I relied on the Test_Info program (it seems to me. Sorry for the imprecision, it's been several months already).
I will do more tests (and probably some modifications in the code) and then come back to you as soon as possible.
Thank you.

**Comment by MatCDev** [comment]
Hi @mcuee,
Is it possible for you to test my last modifications of the library code ?
It should work.
I based the libusbK device identification code on the class guid. It seems to me that this one is unique for libusbK devices.
So to test. If it's ok, I still have 2-3 modifications to make and I have to clean the code.
Thank you.

**Comment by MatCDev** [comment]
If it's not working, can you give me the Class GUID of your libusbK device which you are using for your tests

**Comment by MatCDev** [comment]
Glad to know @mcuee ! I continue to finalize the code, I will come back to you as soon as possible.

**Comment by MatCDev** [comment]
@mcuee do you know if there is a difference between flushing an endpoint pipe or read it until there is no data left in ?
According to the library (LibUsbDotNet) : 
- there is the UsbEndpointBase.Flush() function which is based on an api call to the driver FlushPipe functionnality (i.e. WinUsb_FlushPipe / UsbK_FlushPipe)
- there is also UsbEndpointReader.ReadFlush() function which is based on the Read function until no data left.

**Comment by mcuee** [comment]
@MatCDev 
I am sorry I know very little of libusbdotnet. I am more of a tester in this project.

@qmfrederik 
Please help if you have sometime. Thanks.

**Comment by mcuee** [comment]
Tested to be okay so I take the liberty to merge this. Hopefully it is okay for the v2 branch.

**Comment by MatCDev** [comment]
@mcuee 
If any changes need to be done, just ping me.
I will do them with pleasure to be able to maintain and develop the library 😄

**Comment by mcuee** [comment]
@MatCDev 

Thanks a lot for the offer.

Run log under Windows with latest v2 git (including PR #162 and PR #172 for dotnet 6.0).

The benchmark device is with libusbk driver.

```
PS C:\work\libusb\libusbdotnet_v2>  dotnet build stage/BenchmarkCon/BenchmarkCon.csproj -c Release

Welcome to .NET 6.0!
---------------------
SDK Version: 6.0.404

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
MSBuild version 17.3.2+561848881 for .NET
  Determining projects to restore...
  Restored C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\LibUsbDotNet.csproj (in 5.39 sec).
  Restored C:\work\libusb\libusbdotnet_v2\stage\BenchmarkCon\BenchmarkCon.csproj (in 5.39 sec).
C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\Internal\Kernel32.cs(89,62): warning CS0618: 'UnmanagedType.AsAny' is
 obsolete: 'Marshalling arbitrary types may be unavailable in future releases. Specify the type you wish to marshal as.
' [C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\LibUsbDotNet.csproj]
C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\Internal\Kernel32.cs(99,62): warning CS0618: 'UnmanagedType.AsAny' is
 obsolete: 'Marshalling arbitrary types may be unavailable in future releases. Specify the type you wish to marshal as.
' [C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\LibUsbDotNet.csproj]
C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\Internal\Kernel32.cs(119,70): warning CS0618: 'UnmanagedType.AsAny' i
s obsolete: 'Marshalling arbitrary types may be unavailable in future releases. Specify the type you wish to marshal as
.' [C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\LibUsbDotNet.csproj]
C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\Internal\SetupApi.cs(239,77): warning CS0618: 'UnmanagedType.AsAny' i
s obsolete: 'Marshalling arbitrary types may be unavailable in future releases. Specify the type you wish to marshal as
.' [C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\LibUsbDotNet.csproj]
C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\Internal\SetupApi.cs(296,81): warning CS0618: 'UnmanagedType.AsAny' i
s obsolete: 'Marshalling arbitrary types may be unavailable in future releases. Specify the type you wish to marshal as
.' [C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\LibUsbDotNet.csproj]
C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\WinUsb\Internal\LibusbKAPI.cs(102,78): warning CS0618: 'UnmanagedType
.AsAny' is obsolete: 'Marshalling arbitrary types may be unavailable in future releases. Specify the type you wish to m
arshal as.' [C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\LibUsbDotNet.csproj]
C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\WinUsb\Internal\WinUsbAPI.cs(104,78): warning CS0618: 'UnmanagedType.
AsAny' is obsolete: 'Marshalling arbitrary types may be unavailable in future releases. Specify the type you wish to ma
rshal as.' [C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\LibUsbDotNet.csproj]
C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\LibUsb\Internal\LibUsbRequest.cs(71,30): warning CS0618: 'Marshal.Rea
dByte(object, int)' is obsolete: 'ReadByte(Object, Int32) may be unavailable in future releases.' [C:\work\libusb\libus
bdotnet_v2\stage\LibUsbDotNet\LibUsbDotNet.csproj]
C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\MonoLibUsb\MonoUsbEventHandler.cs(188,25): warning SYSLIB0006: 'Threa
d.Abort()' is obsolete: 'Thread.Abort is not supported and throws PlatformNotSupportedException.' [C:\work\libusb\libus
bdotnet_v2\stage\LibUsbDotNet\LibUsbDotNet.csproj]
C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\Main\UsbDeviceFinder.cs(261,20): warning SYSLIB0011: 'BinaryFormatter
.Deserialize(Stream)' is obsolete: 'BinaryFormatter serialization is obsolete and should not be used. See https://aka.m
s/binaryformatter for more information.' [C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\LibUsbDotNet.csproj]
C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\Main\UsbDeviceFinder.cs(272,13): warning SYSLIB0011: 'BinaryFormatter
.Serialize(Stream, object)' is obsolete: 'BinaryFormatter serialization is obsolete and should not be used. See https:/
/aka.ms/binaryformatter for more information.' [C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\LibUsbDotNet.csproj]
  LibUsbDotNet -> C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\bin\Release\net6.0\LibUsbDotNet.LibUsbDotNet.dll
  BenchmarkCon -> C:\work\libusb\libusbdotnet_v2\stage\BenchmarkCon\bin\Release\net6.0\BenchmarkCon.dll

Build succeeded.

C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\Internal\Kernel32.cs(89,62): warning CS0618: 'UnmanagedType.AsAny' is
 obsolete: 'Marshalling arbitrary types may be unavailable in future releases. Specify the type you wish to marshal as.
' [C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\LibUsbDotNet.csproj]
C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\Internal\Kernel32.cs(99,62): warning CS0618: 'UnmanagedType.AsAny' is
 obsolete: 'Marshalling arbitrary types may be unavailable in future releases. Specify the type you wish to marshal as.
' [C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\LibUsbDotNet.csproj]
C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\Internal\Kernel32.cs(119,70): warning CS0618: 'UnmanagedType.AsAny' i
s obsolete: 'Marshalling arbitrary types may be unavailable in future releases. Specify the type you wish to marshal as
.' [C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\LibUsbDotNet.csproj]
C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\Internal\SetupApi.cs(239,77): warning CS0618: 'UnmanagedType.AsAny' i
s obsolete: 'Marshalling arbitrary types may be unavailable in future releases. Specify the type you wish to marshal as
.' [C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\LibUsbDotNet.csproj]
C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\Internal\SetupApi.cs(296,81): warning CS0618: 'UnmanagedType.AsAny' i
s obsolete: 'Marshalling arbitrary types may be unavailable in future releases. Specify the type you wish to marshal as
.' [C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\LibUsbDotNet.csproj]
C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\WinUsb\Internal\LibusbKAPI.cs(102,78): warning CS0618: 'UnmanagedType
.AsAny' is obsolete: 'Marshalling arbitrary types may be unavailable in future releases. Specify the type you wish to m
arshal as.' [C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\LibUsbDotNet.csproj]
C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\WinUsb\Internal\WinUsbAPI.cs(104,78): warning CS0618: 'UnmanagedType.
AsAny' is obsolete: 'Marshalling arbitrary types may be unavailable in future releases. Specify the type you wish to ma
rshal as.' [C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\LibUsbDotNet.csproj]
C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\LibUsb\Internal\LibUsbRequest.cs(71,30): warning CS0618: 'Marshal.Rea
dByte(object, int)' is obsolete: 'ReadByte(Object, Int32) may be unavailable in future releases.' [C:\work\libusb\libus
bdotnet_v2\stage\LibUsbDotNet\LibUsbDotNet.csproj]
C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\MonoLibUsb\MonoUsbEventHandler.cs(188,25): warning SYSLIB0006: 'Threa
d.Abort()' is obsolete: 'Thread.Abort is not supported and throws PlatformNotSupportedException.' [C:\work\libusb\libus
bdotnet_v2\stage\LibUsbDotNet\LibUsbDotNet.csproj]
C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\Main\UsbDeviceFinder.cs(261,20): warning SYSLIB0011: 'BinaryFormatter
.Deserialize(Stream)' is obsolete: 'BinaryFormatter serialization is obsolete and should not be used. See https://aka.m
s/binaryformatter for more information.' [C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\LibUsbDotNet.csproj]
C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\Main\UsbDeviceFinder.cs(272,13): warning SYSLIB0011: 'BinaryFormatter
.Serialize(Stream, object)' is obsolete: 'BinaryFormatter serialization is obsolete and should not be used. See https:/
/aka.ms/binaryformatter for more information.' [C:\work\libusb\libusbdotnet_v2\stage\LibUsbDotNet\LibUsbDotNet.csproj]
    11 Warning(s)
    0 Error(s)

Time Elapsed 00:00:12.62

PS C:\work\libusb\libusbdotnet_v2\stage\BenchmarkCon\bin\Release\net6.0> .\BenchmarkCon.exe list
LibUsbDotNet USB Benchmark v2.2.0.0
Copyright (c) 2010 Travis Robinson. <libusbdotnet@gmail.com>
website: http://sourceforge.net/projects/libusbdotnet
1. 04D8:FA2E Microchip Technology, Inc. - Benchmark Device

Select device (1-1) :1

Benchmark device 04D8:FFFFFA2E opened..
Loop Test Information
        Vid / Pid       : 04D8h / FFFFFA2Eh
        Interface #     : 00h
        Alt Interface # : 00h
        Priority        : Normal
        Buffer Size     : 4096
        Buffer Count    : 1
        Display Refresh : 1000 (ms)
        Transfer Timeout: 5000 (ms)
        Retry Count     : 0
        Verify Data     : Off

Bulk Read (Ep81h) max packet size: 32
Bulk Write (Ep01h) max packet size: 32

While the test is running:
Press 'Q' to quit
Press 'T' for test details
Press 'I' for status information
Press 'R' to reset averages

Press 'Q' to exit, any other key to begin..
Avg. Bytes/s: 263912.15 Transfers: 61 Bytes/s: 263912.15
Avg. Bytes/s: 262136.93 Transfers: 126 Bytes/s: 260492.54
Avg. Bytes/s: 264085.24 Transfers: 192 Bytes/s: 267886.31
Avg. Bytes/s: 265645.48 Transfers: 259 Bytes/s: 270220.51
Avg. Bytes/s: 265358.39 Transfers: 324 Bytes/s: 264220.59
Avg. Bytes/s: 264111.35 Transfers: 388 Bytes/s: 257973.88
Avg. Bytes/s: 269594.78 Transfers: 463 Bytes/s: 302035.79
Avg. Bytes/s: 271458.63 Transfers: 533 Bytes/s: 284466.71
Avg. Bytes/s: 271638.74 Transfers: 600 Bytes/s: 273080.09
Avg. Bytes/s: 270458.37 Transfers: 664 Bytes/s: 259871.81
Avg. Bytes/s: 270107.26 Transfers: 730 Bytes/s: 266624.95
Avg. Bytes/s: 269835.45 Transfers: 796 Bytes/s: 266865.15
Avg. Bytes/s: 269739.95 Transfers: 862 Bytes/s: 268593.45
Avg. Bytes/s: 269737.57 Transfers: 928 Bytes/s: 269706.51
Avg. Bytes/s: 269220.83 Transfers: 993 Bytes/s: 262053.49
Avg. Bytes/s: 268704.41 Transfers: 1057 Bytes/s: 260938.31
Avg. Bytes/s: 268461.53 Transfers: 1123 Bytes/s: 264630.85
qAvg. Bytes/s: 268555.99 Transfers: 1189 Bytes/s: 270173.41
stopped Ep81h thread.
stopped Ep01h thread.
Loop Test Information
        Vid / Pid       : 04D8h / FFFFFA2Eh
        Interface #     : 00h
        Alt Interface # : 00h
        Priority        : Normal
        Buffer Size     : 4096
        Buffer Count    : 1
        Display Refresh : 1000 (ms)
        Transfer Timeout: 5000 (ms)
        Retry Count     : 0
        Verify Data     : Off

Bulk Read (Ep81h) max packet size: 32
        Total Bytes     : 4874240
        Total Transfers : 1190
        Avg. Bytes/sec  : 268551.98
        Elapsed Time    : 18.15 seconds

Bulk Write (Ep01h) max packet size: 32
        Total Bytes     : 4874240
        Total Transfers : 1190
        Avg. Bytes/sec  : 268553.90
        Elapsed Time    : 18.15 seconds

Press any key to exit..

```

**Comment by mcuee** [comment]
> Hello @mcuee , Do you have any idea about the date of the next release for the last modifications of the v2 version on nuget ? i.e. 2.2.30 ?

Please refer to the discussion here.
https://github.com/LibUsbDotNet/LibUsbDotNet/issues/171

I do not have the permission to upload to Nuget.

@qmfrederik 
Please help here. Thanks.

**Pull request merged**
