### PR TITLE
Hotplug support

### PR DESCRIPTION
**Pull request by sdijoseph**
This is to address #32 by adding hotplug event support, at least on Linux/Mac. Device event notifications for Windows will likely be on a separate PR, as hotplug is not supported on Windows. It is also dependent on PR #193 being merged first, as well as another PR regarding memory management that I will open after #193 is merged. The reason I'm opening a draft for this now is to solicit feedback.

In addition to hotplug, the following has been added in this PR:
1. Classes LocationId and PhyiscalPortId. These classes can be useful for distinguishing devices that have identical VIDs and PIDs and provide no serial number.
   - LocationId is a combination of the BusNumber and PortNumbers properties of a UsbDevice.
   - PhysicalPortId has two LocationsIds, Usb2Id and Usb3Id. This is to identify a physical USB port, as the bus number when a USB 2 device is connected differs from when a USB 3 device is connected.
2. Makes a number of changes to UsbDeviceFinder
   - Adds LocationId and PhysicalPortid.
   - Simplifies the class by adding the init accessor to each property, avoiding the need for multiple overloads.
3. Add DeviceManager class.
   - This class uses hotplug events to add the WaitForDevice method. This method waits for a device's arrival (or returns it immediately if it already was connected at program start). It also takes an optional parameter stableConnectionInterval, which, if set, will ensure the device does not disconnect for the specified interval after it's first arrival. This is useful for situations in which a device may rapidly connect and disconnect from the system, such as during a reboot/reset.

You can try out the WaitForDevice method in the newly added Hotplug example. Configure the device finder for your test device, and the program will wait for it to connect without disconnecting for 2 seconds (it will not wait if the device was already connected at program start). Then it will run the ReadWrite.Async example code. You can test the stableConnectionInterval feature by pressing the reset button on your USB device, if it has one.

Besides needing #193 to be merged first, this PR is really messy in certain places, I need to clean it up over time.

### CODE REVIEW

**Comment by mcuee** [comment]
@sdijoseph 

To make testing easier, I have created the development branch. Could you re-target PR #193 and this PR #216 to the development branch? 

I will merge PR #193 to the development branch right away once you retarget it. Thanks.

**Comment by mcuee** [comment]
@sdijoseph 

On a second thought, this is not really necessary.

**Comment by mcuee** [comment]
Since LocationId and PhysicalPortid are added, it will be good to update Show.Info example as well to include these two properties.

**Comment by mcuee** [comment]
Output of hotplug example is kind of as expected under Windows.
```
PS C:\work\libusb\libusbdotnet\libusbdotnet_pr216> .\src\Examples\Hotplug\bin\Release\net7.0\Hotplug.exe
Unhandled exception. System.PlatformNotSupportedException: This platform does not support hotplug.
   at LibUsbDotNet.LibUsb.UsbContext.RegisterHotPlug() in C:\work\libusb\libusbdotnet\libusbdotnet_pr216\src\LibUsbDotNet\LibUsb\UsbContext.cs:line 154
   at LibUsbDotNet.LibUsb.DeviceManager.Start() in C:\work\libusb\libusbdotnet\libusbdotnet_pr216\src\LibUsbDotNet\LibUsb\DeviceManager.cs:line 24
   at Examples.Hotplug.Main(String[] args) in C:\work\libusb\libusbdotnet\libusbdotnet_pr216\src\Examples\Hotplug\Program.cs:line 71
   at Examples.Hotplug.<Main>(String[] args)
```

**Comment by sdijoseph** [comment]
> @sdijoseph
> 
> Just wondering how do I configure HotPlug example to run the async code? The location id is supposed to be `3-1`.

If you want to find the device by port, change [this](https://github.com/LibUsbDotNet/LibUsbDotNet/blob/56601d0a9fdbce6548e4ebcc9d10494313b8f240/src/Examples/Hotplug/Program.cs#L63) line to:
```
var port = new PhysicalPortId(new LocationId(3, new ReadOnlyCollection<byte>(new byte[] { 1 })), new LocationId(4, new ReadOnlyCollection<byte>(new byte[] { 1 })));
```

But you can also just change the finder to find your device by vendor id:
```
var finder = new UsbDeviceFinder
    {
        Vid = 0x04b4 // Set vendor id here
    };
```

**Comment by mcuee** [comment]
@sdijoseph 

It seems to work under macOS as well. 
```
mcuee@mcuees-Mac-mini net7.0 % ./Hotplug
4/30/2023 11:22:27 AM DeviceArrived VendorId-0x0AC8 ProductId-0x3420 Port-2-2.4.7
4/30/2023 11:22:27 AM DeviceArrived VendorId-0x1A40 ProductId-0x0201 Port-2-2.4.5
4/30/2023 11:22:27 AM DeviceArrived VendorId-0x1A40 ProductId-0x0201 Port-2-2.4
4/30/2023 11:22:27 AM DeviceArrived VendorId-0x0BDA ProductId-0x5411 Port-2-2.1
4/30/2023 11:22:27 AM DeviceArrived VendorId-0x0BDA ProductId-0x5411 Port-2-2
4/30/2023 11:22:27 AM DeviceArrived VendorId-0x05E3 ProductId-0x0749 Port-2-6.1.1
4/30/2023 11:22:27 AM DeviceArrived VendorId-0x0BDA ProductId-0x0411 Port-2-6.1
4/30/2023 11:22:27 AM DeviceArrived VendorId-0x0BDA ProductId-0x0411 Port-2-6
Waiting for device arrival.
4/30/2023 11:22:36 AM DeviceArrived VendorId-0x04D8 ProductId-0xFA2E Port-2-1
Waiting for device disconnect.
Timeout waiting for device disconnect
Got a stable connection.
Write transfer #0 completed @ 11.2338 ms with Error-Success Length-5 Data-7.202
Read transfer #2 completed @ 11.2485 ms with Error-Success Length-5 Data-10.55
Write transfer #2 completed @ 11.2636 ms with Error-Success Length-5 Data-9.777
Write transfer #1 completed @ 11.271 ms with Error-Success Length-6 Data-9.7177
Read transfer #0 completed @ 11.275 ms with Error-Success Length-5 Data-10.55
Read transfer #1 completed @ 11.2787 ms with Error-Success Length-6 Data-10.555
Write transfer #3 completed @ 11.288 ms with Error-Success Length-7 Data-10.0006
Write transfer #4 completed @ 11.2945 ms with Error-Success Length-7 Data-10.0743
Read transfer #3 completed @ 11.5967 ms with Error-Success Length-7 Data-10.5554
Write transfer #5 completed @ 11.6002 ms with Error-Success Length-7 Data-10.1356
Read transfer #4 completed @ 11.6064 ms with Error-Success Length-7 Data-10.5554
Read transfer #5 completed @ 11.6103 ms with Error-Success Length-7 Data-10.5554
Write transfer #6 completed @ 11.6152 ms with Error-Success Length-7 Data-10.2329
Write transfer #7 completed @ 11.6171 ms with Error-Success Length-7 Data-10.3464
Read transfer #6 completed @ 11.6184 ms with Error-Success Length-7 Data-10.5554
Write transfer #8 completed @ 11.6186 ms with Error-Success Length-7 Data-10.4178
Read transfer #7 completed @ 11.62 ms with Error-Success Length-7 Data-10.5554
Read transfer #8 completed @ 11.6468 ms with Error-Success Length-7 Data-10.5554
Write transfer #9 completed @ 11.6507 ms with Error-Success Length-6 Data-10.555
Read transfer #9 completed @ 11.6523 ms with Error-Success Length-6 Data-10.555
Press any key to exit...
```

**Comment by mcuee** [comment]
@sdijoseph 

Somehow the stableConnectionInterval feature does not seem to work as expected under macOS (tested with Mac Mini M1 running latest macOS Ventura 13.3.1 version.

```
mcuee@mcuees-Mac-mini net7.0 % ./Hotplug
4/30/2023 11:34:58 AM DeviceArrived VendorId-0x1915 ProductId-0x1025 Port-2-2.4.5.6
4/30/2023 11:34:58 AM DeviceArrived VendorId-0x046D ProductId-0xC52B Port-2-2.4.6
4/30/2023 11:34:58 AM DeviceArrived VendorId-0x1A40 ProductId-0x0201 Port-2-2.4.5
4/30/2023 11:34:58 AM DeviceArrived VendorId-0x0AC8 ProductId-0x3420 Port-2-2.4.7
4/30/2023 11:34:58 AM DeviceArrived VendorId-0x1A40 ProductId-0x0201 Port-2-2.4
4/30/2023 11:34:58 AM DeviceArrived VendorId-0x0BDA ProductId-0x5411 Port-2-2.1
4/30/2023 11:34:58 AM DeviceArrived VendorId-0x0BDA ProductId-0x5411 Port-2-2
4/30/2023 11:34:58 AM DeviceArrived VendorId-0x05E3 ProductId-0x0749 Port-2-6.1.1
4/30/2023 11:34:58 AM DeviceArrived VendorId-0x0BDA ProductId-0x0411 Port-2-6.1
4/30/2023 11:34:58 AM DeviceArrived VendorId-0x0BDA ProductId-0x0411 Port-2-6
Waiting for device arrival.
4/30/2023 11:35:01 AM DeviceArrived VendorId-0x04D8 ProductId-0xFA2E Port-2-2.4.3 (first plug-in)
4/30/2023 11:35:05 AM DeviceLeft VendorId-0x04D8 ProductId-0xFA2E Port-2-2.4.3 (hit reset button)
4/30/2023 11:35:06 AM DeviceArrived VendorId-0x04D8 ProductId-0xFA2E Port-2-2.4.3
4/30/2023 11:35:08 AM DeviceLeft VendorId-0x04D8 ProductId-0xFA2E Port-2-2.4.3 (hit reset button)
4/30/2023 11:35:08 AM DeviceArrived VendorId-0x04D8 ProductId-0xFA2E Port-2-2.4.3

```

**Comment by sdijoseph** [comment]
> @sdijoseph
> 
> Somehow the stableConnectionInterval feature does not seem to work as expected under macOS (tested with Mac Mini M1 running latest macOS Ventura 13.3.1 version.

That's odd, it seems the first device arrival is not being triggered at all, as there is no `Waiting for device disconnect` statement. What were your device finder settings? I notice the 2nd example is on a different port.

**Comment by mcuee** [comment]
> That's odd, it seems the first device arrival is not being triggered at all, as there is no `Waiting for device disconnect` statement. What were your device finder settings? I notice the 2nd example is on a different port.

I see. It is monitoring device 2-1.        
```
var port = new PhysicalPortId(new LocationId(2, new ReadOnlyCollection<byte>(new byte[] { 1 })), new LocationId(1, new ReadOnlyCollection<byte>(new byte[] { 1 })));
```

So are you saying only device configured for monitoring will have this `stableConnectionInterval` feature, right? In that case, macOS behavior is as expected. I need to check back under Ubuntu Linux. It seems to me the behavior there is different.

**Comment by mcuee** [comment]
I think I understand now, Only the monitored device has the stableConnectionInterval featuee. And the feature is not applicable after the finish of the async read-write example.

Ubuntu 20.04 Linux running log. Monitoring port 3-1. 

```
mcuee@UbuntuSwift3:~/build/libusb/libusbdotnet_pr216$ ./src/Examples/Hotplug/bin/Release/net7.0/Hotplug 
04/30/2023 13:26:37 DeviceArrived VendorId-0x1D6B ProductId-0x0003 Port-4
04/30/2023 13:26:37 DeviceArrived VendorId-0x1C7A ProductId-0x0575 Port-3-7
04/30/2023 13:26:37 DeviceArrived VendorId-0x04F2 ProductId-0xB6DD Port-3-5
04/30/2023 13:26:37 DeviceArrived VendorId-0x046D ProductId-0xC52B Port-3-3
04/30/2023 13:26:37 DeviceArrived VendorId-0x05E3 ProductId-0x0610 Port-3-2
04/30/2023 13:26:37 DeviceArrived VendorId-0x8087 ProductId-0x0026 Port-3-10
04/30/2023 13:26:37 DeviceArrived VendorId-0x1D6B ProductId-0x0002 Port-3
04/30/2023 13:26:37 DeviceArrived VendorId-0x05E3 ProductId-0x0612 Port-2-1
04/30/2023 13:26:37 DeviceArrived VendorId-0x1D6B ProductId-0x0003 Port-2
04/30/2023 13:26:37 DeviceArrived VendorId-0x1D6B ProductId-0x0002 Port-1
Waiting for device arrival.
04/30/2023 13:26:41 DeviceArrived VendorId-0x04D8 ProductId-0xFA2E Port-3-2.3 (first plug in)
04/30/2023 13:26:47 DeviceLeft VendorId-0x04D8 ProductId-0xFA2E Port-3-2.3 (reset)
04/30/2023 13:26:48 DeviceArrived VendorId-0x04D8 ProductId-0xFA2E Port-3-2.3
04/30/2023 13:26:49 DeviceLeft VendorId-0x04D8 ProductId-0xFA2E Port-3-2.3 (reset)
04/30/2023 13:26:50 DeviceArrived VendorId-0x04D8 ProductId-0xFA2E Port-3-2.3
04/30/2023 13:26:54 DeviceLeft VendorId-0x04D8 ProductId-0xFA2E Port-3-2.3 (unplug)
04/30/2023 13:27:00 DeviceArrived VendorId-0x04D8 ProductId-0xFA2E Port-3-1 (plug in the monitored port)
Waiting for device disconnect.
Timeout waiting for device disconnect
Got a stable connection.
Write transfer #2 completed @ 5.7482 ms with Error-Success Length-6 Data-4.3562
Write transfer #0 completed @ 5.7508 ms with Error-Success Length-6 Data-3.0072
Write transfer #1 completed @ 5.7528 ms with Error-Success Length-6 Data-4.3254
Write transfer #3 completed @ 5.7573 ms with Error-Success Length-6 Data-4.3823
Write transfer #4 completed @ 5.7612 ms with Error-Success Length-6 Data-4.3928
Read transfer #0 completed @ 5.7635 ms with Error-Success Length-6 Data-4.5308
Read transfer #2 completed @ 5.7659 ms with Error-Success Length-6 Data-4.5308
Read transfer #1 completed @ 5.7678 ms with Error-Success Length-6 Data-4.5308
Read transfer #4 completed @ 6.0297 ms with Error-Success Length-6 Data-4.5308
Read transfer #3 completed @ 6.0478 ms with Error-Success Length-6 Data-4.5308
Write transfer #6 completed @ 6.0542 ms with Error-Success Length-6 Data-4.4406
Write transfer #5 completed @ 6.0591 ms with Error-Success Length-6 Data-4.4151
Read transfer #5 completed @ 6.0639 ms with Error-Success Length-6 Data-4.5308
Write transfer #7 completed @ 6.0682 ms with Error-Success Length-5 Data-4.488
Read transfer #6 completed @ 6.0746 ms with Error-Success Length-6 Data-4.5308
Write transfer #8 completed @ 6.0755 ms with Error-Success Length-6 Data-4.5051
Read transfer #7 completed @ 6.0773 ms with Error-Success Length-5 Data-4.530
Write transfer #9 completed @ 6.0903 ms with Error-Success Length-6 Data-4.5308
Read transfer #8 completed @ 6.0922 ms with Error-Success Length-6 Data-4.5308
Read transfer #9 completed @ 6.095 ms with Error-Success Length-6 Data-4.5308
Press any key to exit...
04/30/2023 13:27:08 DeviceLeft VendorId-0x04D8 ProductId-0xFA2E Port-3-1 (reset)
04/30/2023 13:27:09 DeviceArrived VendorId-0x04D8 ProductId-0xFA2E Port-3-1
04/30/2023 13:27:10 DeviceLeft VendorId-0x04D8 ProductId-0xFA2E Port-3-1 (reset)
04/30/2023 13:27:10 DeviceArrived VendorId-0x04D8 ProductId-0xFA2E Port-3-1
```

**Comment by mcuee** [comment]
@qmfrederik 

When you have some time, please review this PR as well after you review PR #193. Thanks.

**Comment by mcuee** [comment]
@sdijoseph 

Please rebase this PR now that PR #193 has been merged. Then @qmfrederik will review this PR. Thanks.

**Comment by mcuee** [comment]
@sdijoseph 
Thanks for rebasing the PR.

@qmfrederik 
Please help to review and give your feedbacks. Thanks.

**Comment by mcuee** [comment]
@GreenShadeZhang and @MatCDev

I understand that you are mostly using the V2 branch. With #193 merged, the master branch will be pretty close to V2 branch in terms of capability.

The main remaining missing feature is hotplug support which even the V2 branch does not support welll. 

If you have some time, please give this PR a try under Linux or macOS. 

As mentioned by @sdijoseph, "Device event notifications for Windows will likely be on a separate PR, as hotplug is not supported on Windows."

**Comment by sdijoseph** [comment]
> @qmfrederik 
> 
> Sorry to ping you. Just wondering if you have sometime to review this PR. Thanks.

Also, if/when this gets merged, please release another NuGet build, a lot of features have been added.

**Comment by sdijoseph** [comment]
@qmfrederik When you are able to review this, in addition to triggering another NuGet build and enabling the GitHub Pages deployment, could you please give someone else the ability to trigger NuGet builds (perhaps @mcuee)?

**Comment by mcuee** [comment]
@qmfrederik 

Sorry to ping you again. Please help here. Thanks.

**Comment by qmfrederik** [comment]
I've done a cursory review of this PR and it looks good to me.  @sdijoseph is there anything else you want to do on this branch or do you consider it ready to merge?

**Review by qmfrederik — APPROVED** [review]

**Comment by mcuee** [comment]
@qmfrederik 
Thanks a lot for approving this PR. I will just merge this PR so that other users can test this easier.

I believe @sdijoseph will be able to help out when there are issues.

**Pull request merged**
