### PR TITLE
Create build.yaml for v2 branch

### PR DESCRIPTION
**Pull request by mcuee**
This is copied from the github action from the master branch.

### CODE REVIEW

**Comment by mcuee** [comment]
Hopefully this can server as a basic check for the v2 branch. This should fix #175.
* https://github.com/LibUsbDotNet/LibUsbDotNet/issues/175

**Comment by GreenShadeZhang** [comment]
Can this github action update the version of the nuget package source?

**Comment by mcuee** [comment]
> Can this github action update the version of the nuget package source?

No, it can not.

**Comment by GreenShadeZhang** [comment]
> > Can this github action update the version of the nuget package source?
> 
> No, it can not.

I see that there are some updates to the recent master branch, and the development of new features in the future can be committed in master, right?

**Comment by mcuee** [comment]
> > > Can this github action update the version of the nuget package source?
> > 
> > 
> > No, it can not.
> 
> I see that there are some updates to the recent master branch, and the development of new features in the future can be committed in master, right?

Master branch will be the main focus for development. You are welcome to contribute to the master branch, like new features, bug fixes, new examples, etc.

Right now it is missing the async feature that PR #193 will address. 
* https://github.com/LibUsbDotNet/LibUsbDotNet/issues/144
* #193

It is also missing the Device Notifier feature but there is a problem that libusb does not support hotplug under Windows. So maybe that issue may not be sorted out soon. One potential solution is to use libusb-1.0 hotplug for Linux and macOS and then use Windows Forms under Windows.
* https://github.com/LibUsbDotNet/LibUsbDotNet/issues/32#issuecomment-424393434

**Comment by mcuee** [comment]
> > > Can this github action update the version of the nuget package source?
> > 
> > 
> > No, it can not.
> 
> I see that there are some updates to the recent master branch, and the development of new features in the future can be committed in master, right?

That being said, you are also welcome to contribute to the v2 branch as there are still many users for the v2 branch.

**Comment by GreenShadeZhang** [comment]
Thanks for answering, I refer to some documentation to see if I can make some contributions.

**Pull request merged**
