### PR TITLE
Use manual marshaling in GetDeviceDescriptor() in Mono and .NET Framework

### PR DESCRIPTION
**Pull request by claunia**
where the automatic one, that works in .NET Core, doesn't work.

### CODE REVIEW

**Comment by claunia** [comment]
May fix #30

**Comment by SimantoR** [comment]
Has this been tested? This should be tested and merged. Looks like a good update. @qmfrederik. I can try it on mono on Ubuntu 18.04

**Comment by mcuee** [comment]
@qmfrederik 

Is this PR still necessary? If not we can close it.

**Comment by mcuee** [comment]
@claunia 

Issue #30 has been closed. Do you think if this PR is still needed? Thanks. If yes, please rebase to the git HEAD.

**Comment by mcuee** [comment]
BTW, I think this is only for the v2 branch.

**Comment by mcuee** [comment]
I will clost this old PR for now. If someone encounter the same issue, please open a new PR. Thanks.

**Pull request closed without merging**
